### ISSUE TITLE
error when running alntools -h

### ISSUE THREAD

**Issue by mfrancesconi81** [churchill-lab/alntools#1]
Hi,

I want to perform ASE using EMASE, which seems to me a very good tool but I couldn't make it to work so far. I got stuck immediatly with the preparation of the Alignment incident matrix file with alntools. 

I installed alntools following instructions here https://churchill-lab.github.io/alntools/

Installation finished successfully but then I got an error already when trying to run alntools -h (see below)

Traceback (most recent call last):
  File "/software/bl/el7.2/anaconda2/envs/alntools/bin/alntools", line 4, in <module>
    __import__('pkg_resources').run_script('alntools==0.1.0', 'alntools')
  File "/software/bl/el7.2/anaconda2/envs/alntools/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/bl/el7.2/anaconda2/envs/alntools/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/nfs/software/bl/el7.2/anaconda2/envs/alntools/lib/python2.7/site-packages/alntools-0.1.0-py2.7.egg/EGG-INFO/scripts/alntools", line 11, in <module>
    from alntools.cli import cli
  File "/software/bl/el7.2/anaconda2/envs/alntools/lib/python2.7/site-packages/alntools-0.1.0-py2.7.egg/alntools/cli.py", line 6, in <module>
    from alntools import methods
  File "/software/bl/el7.2/anaconda2/envs/alntools/lib/python2.7/site-packages/alntools-0.1.0-py2.7.egg/alntools/methods.py", line 15, in <module>
    from alntools.matrix.AlignmentPropertyMatrix import AlignmentPropertyMatrix as APM
ImportError: No module named matrix.AlignmentPropertyMatrix

Any clues?
thanks,
 
Mirko

**Comment by kbchoi-jax** [comment]
Hi Mirko,

Sorry we've been updating `alntools` a lot since the documentation. We will package it up soon so you can install it much more easily, but for now please do the following. First remove your current conda virtual environment like this.
```
conda remove -n alntools --all --force
```
Then try to reinstall like this.

```
git clone https://github.com/churchill-lab/alntools.git alntools
cd alntools
conda create -n alntools python=2 numpy=1.8.2 scipy=0.13.3 pytables six cython pysam click flask future biopython
source activate alntools
python setup.py install
```
This should do the trick.

**Comment by mfrancesconi81** [comment]
It worked,

thanks!
