### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by asreedasyam** [churchill-lab/alntools#14]
Hello,
I'm having trouble installing alntools. I followed the instructions on the GitHub page (https://churchill-lab.github.io/alntools/), but I'm encountering an error when trying to run the tool.
Since EMASE installation through conda failed, I skipped it and installed all the other dependencies manually. Running the setup.py script didn't produce any errors, but I get the following error message when I try to use alntools.
Any help troubleshooting this installation issue would be greatly appreciated.

`Traceback (most recent call last):
  File "/home/user2/tools/conda_envs/ase/bin/alntools", line 4, in <module>
    __import__('pkg_resources').run_script('alntools==0.1.1', 'alntools')
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/EGG-INFO/scripts/alntools", line 11, in <module>
    from alntools.cli import cli
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/alntools/cli.py", line 9, in <module>
    from . import bin_utils
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/alntools/bin_utils.py", line 13, in <module>
    from .matrix.AlignmentPropertyMatrix import AlignmentPropertyMatrix as APM
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/alntools/matrix/AlignmentPropertyMatrix.py", line 3, in <module>
    import tables
  File "/home/user2/tools/conda_envs/ase/lib/python2.7/site-packages/tables/__init__.py", line 82, in <module>
    from tables.utilsextension import (
ImportError: libhdf5.so.6: cannot open shared object file: No such file or directory`

**Comment by mattjvincent** [comment]
Do you have the HDF libraries installed?

**Comment by asreedasyam** [comment]
Hi Matt, Yes, I have installed h5py. I tried with an older version too h5py=2.6.0 but no luck. Thanks !

**Comment by mattjvincent** [comment]
I see you are using Conda.  Can you install alntools directly from source?  I am curious as to where you LD_LIBRARY_PATH is pointing?

`export LD_LIBRARY_PATH=[actual location]`

Also, what are you trying to do with alntools?  Some of the functionality maybe in [GBRS](https://github.com/churchill-lab/gbrs) (including EMASE).

**Comment by asreedasyam** [comment]
Ah!! I was trying to use emase-zero for allele-specific expression, but GBRS seems to be the tool I should use. Thanks for the tip.
