### ISSUE TITLE
bam2ec error chunks=NoneType

### ISSUE THREAD

**Issue by moniekvanselst** [churchill-lab/alntools#6]
Hello,

I am trying to run alntools, because i want to use emase-zero afterwards. Unfortunately i keep getting this error, it said that the variable "chunks" is a NonType and gives an error for trying to calculate the length(see full error message below). Changing the -c (chunks) value does not seem to have any effect on the matter. I also tried running bam2emase, but this give me the same error. Further I tried running it with different bam files (that have been accepted by other, similar tools), this also gave the same error.

Do you have any suggestions on how to fix this error?

**full error:**
 Traceback (most recent call last):
  File "/opt/conda/bin/alntools", line 4, in <module>
    __import__('pkg_resources').run_script('alntools==0.1.1', 'alntools')
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/EGG-INFO/scripts/alntools", line 29, in <module>
    cli()
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/alntools/cli.py", line 75, in bam2ec
    methods.bam2ec(bam_file, ec_file, chunks, directory, number_processes, rangefile, sample, targets)
  File "/opt/conda/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/alntools/methods.py", line 32, in bam2ec
    bam_utils.convert(bam_filename, ec_filename, None, num_chunks=chunks, number_processes=number_processes, temp_dir=directory, range_filename=range_filename, sample=sample, target_filename=target_filename)
  File "/opt/conda/lib/python2.7/site-packages/alntools-0.1.1-py2.7.egg/alntools/bam_utils.py", line 642, in convert
    LOG.info("{:,} chunks calculated in {}, total time: {}".format(len(chunks),
TypeError: object of type 'NoneType' has no len()

**Comment by kbchoi-jax** [comment]
Could you show me the first few lines of your bam file except the header please? It also helps if you give me some more info regarding the experimental settings and your goals. If you prefer  to keep it confidencial, email me at kb.choi@jax.org.

**Comment by nikhilmilind** [comment]
Hello! Any fix for this yet? I have the same issue with a BAM file I generated using STAR...

**Comment by kbchoi-jax** [comment]
Hi NMilind, could you share your bam file? Please contact me at kb.choi@jax.org.
